sonar.projectKey=livros
sonar.projectName=Livros
sonar.sources=app,routes,resources/views,resources/js,resources/css,public/js,database/migrations,database/seeders,config
sonar.tests=tests
sonar.sourceEncoding=UTF-8
